### PR TITLE
Db multi reagent

### LINKED ISSUE #361: db: support linking multiple reagents to one assay result
- make short term fixes to the db schema to allow association of multiple reagents with one assay well result

Notes:
- as part of this, will combine reagent fields for each reagent into one field in the results display, separating the values by two spaces
    - "Small Mol HMS LINCS ID" and "Small Mol Name" 
    - "Cell Name" and "Cell HMS LINCS ID"
    - "Protein Name" and "Protein HMS LINCS ID"
    - and so on
- the title for each included column must be specified by the curator
- for legacy datasets, the titles can be assigned by default, proposed to simply name them:
    - "Small Molecule", "Protein", "Cell", etc.
    - for "legacy" datasets, there are only one of each
- for the API, fields will still be separate
   - currently, API names are constructed from the DWG name (if available, otherwise from the HMS name), converting it to CamelCase (with lower case first letter):
   - example (see  http://lincs.hms.harvard.edu/db/api/v1/dataset/?format=json for instance): 
       - current DWG name: "SM_Center_Compound_ID"
       - current HMS UI display name: "Small Mol HMS LINCS ID"
       - current API result data name: "smCenterCompoundID"
       - other API names currently:
       - smSalt, smCenterSampleID, smLincsID, smName
   - New names:
       - HMS UI display name (to be assigned by curator), for example: "Small Molecule 1"
       - new API names generated: 
           - "smallMolecule1_smCenterCompoundID"
           - "smallMolecule1_smSalt"
           - "smallMolecule1_smCenterSampleID"
           - "smallMolecule1_smLincsID"
           - "smallMolecule1_smName"
@dwrobel1

### PR DESCRIPTION
**Pull request by seanderickson**
resolves #361 support linking multiple reagents to one assay result
- relevant changes begin at commit https://github.com/hmslincs/hmslincs/commit/ffe86a560b35e042369f4d220fd2b6ab5eda9fa9
- includes preliminary work for #357; antibody table is not used at time, included to avoid rebase of work already completed

### CODE REVIEW

**Comment by seanderickson** [comment]
@jmuhlich this should be ready to deploy

**Comment by jmuhlich** [comment]
:+1: after code review with @seanderickson

**Comment by jmuhlich** [comment]
@seanderickson go ahead and deploy it. :)

**Comment by seanderickson** [comment]
gr8 thx!

**Pull request merged**
