### PR TITLE
Db 389 download performance

### LINKED ISSUE #389: db: dataset result downloads take a long time
* specifically, for the new 'large' dataset http://lincs.hms.harvard.edu/db/datasets/20236/results
* the process could be sped up, I believe, if we wrote the output file to a temp directory on disk before streaming through the HTTP response: here https://github.com/hmslincs/hmslincs/blob/master/django/db/views.py#L2371
* also, caching the download could be useful

### PR DESCRIPTION
**Pull request by seanderickson**
resolves #389

### CODE REVIEW

**Comment by seanderickson** [comment]
Note: we may wish to compress the returned data:
for Dataset 20236:
- 96k datarecords - 11 MB xlsx file 
- 1.6x10^6 datapoints - 230 MB csv file

**Comment by seanderickson** [comment]
- Note that BytesIO is no longer being used. Indeed, as we've covered already, there is no *performance* benefit to writing to a temp file.  See commit  notes. This is done because the "optimized_write" mode for openpyxl is incompatible with save_virtual_workbook, so this save_virtual_workbook is not being used.  See https://bitbucket.org/openpyxl/openpyxl/issues/375/use-save_virtual_workbook-and-optimized
- XlsxWriter writes faster by default, and supports writing to a buffer. Its an additional library though.
- yes, StreamingHttpResponse is Django >1.5; I was trying to avoid that
- also note; time spent writing the xlsx file (either to disk, or to memory) is ~1minute; of which most of the time is spent generating the xlsx; time spent iterating over the query cursor and reading the file to the response is <10seconds.

**Comment by jmuhlich** [comment]
Sorry, I didn't understand what optimized_write was doing. Looks like it avoids keeping internal openpyxl data structures in memory while writing the file out, so still a memory savings rather than a cpu time savings. I assume the data structures required to hold the contents of an 11MB xlsx file are pretty big (indeed I just tried to open the xlsx download of dataset 20236 using openpyxl's default non-streaming reader, and I killed the python process when it got to 5 gigs of memory without finishing) so optimized_write is probably *necessary* to even get the thing written out at all.

On dev just now, it took 3m30s for the server to prepare the xlsx of 20236 for download. Is that running this PR now or some older code?

**Comment by seanderickson** [comment]
- That is running with this current PR. For a comparison, the CVS download for that dataset takes ~44sec, so that is a fair estimate of how much of the time is spent in streaming the data from the postgres server.
- also, the "optimized_write" sped things up, but in my testing on my sandbox, I also found that the openpyxl version 1.8.x was about 2x slower than the 2.2.x version (so that version, on sandbox, was more on the order of 90 sec)

**Comment by seanderickson** [comment]
Here are some stats: from dev.osher for the url: 
https://dev.oshernatprod.hms.harvard.edu/db/datasets/20236/results?output_type=.xlsx

sql query time for all runs: ~27sec

openpxl 1.8, optimized, write_only mode, writing to temp file:
writing to file: 2:58 (m:s), total: 3:25
openpxl 2.2, optimized, write_only mode, writing to temp file:
writing to file: 2:15, total: 2:41
XlsxWriter 0.7.3, StringIO
writing: 2:10, total: 2:36

**Comment by jmuhlich** [comment]
I watched the django.cgi memory usage on orchestra while fetching xlsx from 20236. It gradually climbed to ~130MB, I suspect while doing the db query and retrieving results. Then it sat there for a couple of minutes, finally shooting up to ~140MB in a few seconds before ending. The resulting download file was about 10MB, so the final memory allocation burst was probably the SpooledTemporaryFile buffer. So for dataset downloads, it seems like the SpooledTemporaryFile memory usage is dwarfed by the other stuff and buffering the entire file in memory is fine. However that total memory usage is not great, especially on a shared webserver.

**Comment by jmuhlich** [comment]
The more I think about it, we should definitely put a max_size in just to limit the damage from a bug or unexpected usage producing enormous download files and thus enormous memory allocation. Once we're specifying it, might as well keep it to a more reasonable size than 10MB (assuming we will reduce the query results memory usage making 10MB significant). The kinomescan and kinativ datasets, which make up the majority of our datasets, all produce files under 50KB. I think 100KB seems like a good max_size. I'll file a separate bug on this.

**Pull request merged**
