### PR TITLE
DB fixes for errors in admin email logs

### PR DESCRIPTION
**Pull request by seanderickson**
- fixes for uncaught exceptions on the production server

### CODE REVIEW

**Comment by jmuhlich** [comment]
Is the "No Content" fix meant to address a specific problem? I suppose for an API that's a reasonable response but to a human with a browser it just makes the download links seem to do nothing. Maybe that's fine since if the search result is empty people probably won't click on the download link anyway.

**Comment by jmuhlich** [comment]
Anyway, looks good. :+1:

**Comment by seanderickson** [comment]
fyi - the "No Content" fix relates a dead link - for example, the query for the "cells" on dataset 20235 now returns an empty query, because those cell entries were converted to primary cells.  So the query for http://lincs.hms.harvard.edu/db/datasets/20235/cells?output_type=.xlsx is not referenced in the UI anymore, but the link is broken (it is being hit by a bot, I guess).

**Comment by jmuhlich** [comment]
Ah. I was thinking of a search with zero hits like this, since it ends 
up using the same code path:

http://lincs.hms.harvard.edu/db/sm/?search=uadsgvfdajfbgvjdbfv&extra_form_shown=&dataset_types=

**Pull request merged**
